INSERT INTO vehicles (brand, model)
VALUES 
('Suzuki', 'XL7'),
('Suzuki', 'Ertiga'),
('Mitsubishi', 'Expander'),
('Toyota', 'Innova Reborn'),
('Toyota', 'Innova Zenix'),
('Denza', 'Denza DS'),
('BYD', 'BYD M6'),
('BYD', 'BYD M6 Superior'),
('Aeon', 'Aeon'),
('Hyundai', 'Hyundai ...'),
('Daihatsu', 'Daihatsun Go'),
('Toyota', 'Calya'),
('Daihatsu', 'Sigra'),
('Toyota', 'Avanza All New'),
('Daihatsu', 'Xenia All New'),
('Wuling', 'Confero'),
('Wuling', 'Cortez'),
('Honda', 'Mobilio'),
('Honda', 'HRV'),
('Honda', 'BRV'),
('Hyundai', 'Ioniq 6'),
('Hyundai', 'Ioniq 5');
INSERT INTO motorcycles (brand, model)
('Honda', 'CBR150R'),
('Honda', 'Vario 150'),
('Honda', 'Vario 125'),
('Honda', 'Beat'),
('Yamaha', 'NMAX'),
('Yamaha', 'Aerox 155'),
('Yamaha', 'Mio M3'),
('Suzuki', 'GSX-R150'),
('Suzuki', 'Satria F150'),
('Kawasaki', 'Ninja 250'),
('Kawasaki', 'KLX 150'),
('Vespa', 'Primavera'),
('Vespa', 'Sprint'),
('TVS', 'Apache RTR 200'),
('Benelli', 'TNT 250'),
('Kymco', 'Like 150i');